info = {
    "Competidores": [
        {
            "Nombre": "María González",
            "ID": 1,
            "Edad": 22,
            "Nacionalidad": "Venezuela",
            "Categoría": "Natación",
            "Test": "Blanco",
        },
        {
            "Nombre": "Juan Pérez",
            "ID": 2,
            "Edad": 25,
            "Nacionalidad": "Argentina",
            "Categoría": "Atletismo",
            "Test": "Negro",
        },
        {
            "Nombre": "Ana Silva",
            "ID": 3,
            "Edad": 18,
            "Nacionalidad": "Venezuela",
            "Categoría": "Natación",
            "Test": "Blanco",
        },
        {
            "Nombre": "Pedro López",
            "ID": 4,
            "Edad": 27,
            "Nacionalidad": "Colombia",
            "Categoría": "Natación",
            "Test": "Blanco",
        },
        {
            "Nombre": "Sofia Martínez",
            "ID": 5,
            "Edad": 21,
            "Nacionalidad": "Ecuador",
            "Categoría": "Atletismo",
            "Test": "Blanco",
        },
        {
            "Nombre": "Diego Fernandez",
            "ID": 6,
            "Edad": 26,
            "Nacionalidad": "Argentina",
            "Categoría": "Atletismo",
            "Test": "Blanco",
        },
        {
            "Nombre": "Carmen Mendez",
            "ID": 7,
            "Edad": 23,
            "Nacionalidad": "Colombia",
            "Categoría": "Natación",
            "Test": "Blanco",
        },
        {
            "Nombre": "María Blanco",
            "ID": 8,
            "Edad": 19,
            "Nacionalidad": "Ecuador",
            "Categoría": "Atletismo",
            "Test": "Blanco",
        },
        {
            "Nombre": "Pepe Martin",
            "ID": 9,
            "Edad": 22,
            "Nacionalidad": "México",
            "Categoría": "Atletismo",
            "Test": "Blanco",
        },
        {
            "Nombre": "Jessica Colmenares",
            "ID": 10,
            "Edad": 24,
            "Nacionalidad": "México",
            "Categoría": "Atletismo",
            "Test": "Blanco",
        },
        {
            "Nombre": "Jose González",
            "ID": 11,
            "Edad": 20,
            "Nacionalidad": "Venezuela",
            "Categoría": "Gimnasia",
            "Test": "Blanco",
        },
        {
            "Nombre": "Gabriela Hernández",
            "ID": 12,
            "Edad": 22,
            "Nacionalidad": "Ecuador",
            "Categoría": "Gimnasia",
            "Test": "Blanco",
        },
    ],
    "Equipos": [
        {
            "Categoría": "Natación",
            "Nacionalidad": "Venezuela",
            "Competidores": [1, 3],
            "ID": 1,
        },
        {
            "Categoría": "Atletismo",
            "Nacionalidad": "Argentina",
            "Competidores": [2, 6],
            "ID": 2,
        },
        {
            "Categoría": "Natación",
            "Nacionalidad": "Colombia",
            "Competidores": [4, 7],
            "ID": 3,
        },
        {
            "Categoría": "Atletismo",
            "Nacionalidad": "Ecuador",
            "Competidores": [5, 8],
            "ID": 4,
        },
        {
            "Categoría": "Atletismo",
            "Nacionalidad": "México",
            "Competidores": [9, 10],
            "ID": 5,
        },
    ],
    "Competencias": [
        {
            "Categoría": "Natación 50m Libre Individual",
            "Tipo": "Individual",
            "Competidores": [1, 3, 4, 7],
            "Fecha": "02-08-2024",
        },
        {
            "Categoría": "Atletismo 100m Velocidad Individual",
            "Tipo": "Individual",
            "Competidores": [2, 5, 6, 8, 9, 10],
            "Fecha": "04-08-2024",
        },
        {
            "Categoría": "Gimnasia Artística Individual",
            "Tipo": "Individual",
            "Competidores": [11, 12],
            "Fecha": "05-08-2024",
        },
        {
            "Categoría": "Natación Relevo 4x100m",
            "Tipo": "Equipos",
            "Competidores": [1, 3],
            "Fecha": "05-08-2024",
        },
        {
            "Categoría": "Atletismo Relevo 4x400m",
            "Tipo": "Equipos",
            "Competidores": [2, 4, 5],
            "Fecha": "07-08-2024",
        },
    ],
}
